### PR TITLE
Update DLL to 2.3.2

### PR DESCRIPTION
**Pull request by lgarner**
Dictionary Serialization fix for IOS (Send JsonObject format to server for tags). Next server version is NOT compatible with 2.1.3 due to data type change of tags (2.3.x required).

* Works with Unity 2019.4.10f1, with Xcode 12.2, Visual Studio 8.8.2, IOS 14.2 *

Related Branch on commit history: EDGECLOUD-3907: Objective C Unity Extra Device Info

### CODE REVIEW

**Review by brucearmstrong — APPROVED** [review]
Looks perfect to my human eyes.

**Review by ah1053 — APPROVED** [review]
Works with ios_plugin_device_info branch, Thanks @lgarner

**Review by ah1053 — COMMENTED** [review]
After the update, the SDK throws an exception on my iPhone  iOS 14.1 & Unity 2019.3.5f1
Screen Shot 2020-11-27 at 12 54 24 PM

**Comment by lgarner** [comment]
I'll recheck. I only have 14.2.

> After the update, the SDK throws an exception on my iPhone iOS 14.1 & Unity 2019.3.5f1
> Screen Shot 2020-11-27 at 12 54 24 PM

**Comment by lgarner** [comment]
I changed base to staging_2.1.z for a single merge per discussion.

**Comment by ah1053** [comment]
Tested again on QA-DME and it's working fine

**Comment by lgarner** [comment]
Fixed merge conflict. Keeping original branch.

**Review by franklin-huang-mobiledgex — APPROVED** [review]

**Pull request merged**
