### PR TITLE
Add Dispose() call to MobiledgeXIntegration.cs

### PR DESCRIPTION
**Pull request by lgarner**
On the tin. EdgeManger.cs needs integration.Dispose(), and null inside OnDestroy() as well for both gRPC and REST.

### CODE REVIEW

**Review by brucearmstrong — APPROVED** [review]

**Review by franklin-huang-mobiledgex — APPROVED** [review]

**Comment by ah1053** [comment]
Tested it and it's working fine.
I wonder about the version number jumping from 2.4.1 to 2.5.2

**Comment by lgarner** [comment]
> Tested it and it's working fine.
> I am confused about the version number jumping from 2.4.1 to 2.5.2

Version update is just indicating post 2.4.x release features/changes.

**Review by ah1053 — APPROVED** [review]
Thanks

**Comment by lgarner** [comment]
Looks good. Let me know if you need me to merge it.

**Pull request merged**
