### PR TITLE
add .meta files that were deleted

### PR DESCRIPTION
**Pull request by franklin-huang-mobiledgex**
minor pr. Git was giving me grief about these files each time I pulled

### CODE REVIEW

**Comment by franklin-huang-mobiledgex** [comment]
The meta should only change when I replace the dll. However, I accidently deleted the other files for some reason, so I think these should be new.

**Comment by franklin-huang-mobiledgex** [comment]
Although, it seems like there are no issues in Master (or in this branch) when I import via git url, so not sure what is going on

**Comment by lgarner** [comment]
Let me know, I've bumped meta files for the current binary usage.

**Comment by lgarner** [comment]
I've been not updating the SDK at all for binary file changes, and it seems fine. The UIDs shouldn't be changing anyway...it's how Unity knows that when files moved aroun, they are the same files. Regenerate them, and it no longer knows how to do that.

**Pull request closed without merging**
